replicaCount: 1
image:
  repository: devacr301225.azurecr.io/assignment-service
  tag: f0a8e424b15001f6229dfe31e2a0bae77266e834
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
env:
  SERVER_PORT: "8080"
  ASSIGNMENT_DB_URL: "postgres://pgadmin:Strong@123@dev-postgres301225.postgres.database.azure.com:5432/assignmentdb?sslmode=require"
  # Inter-service communication
  ASSET_SERVICE_BASE_URL: http://asset-service.it-asset.svc.cluster.local
  EMPLOYEE_SERVICE_BASE_URL: http://employee-service.it-employee.svc.cluster.local
ingress:
  enabled: true
  className: azure/application-gateway
  host: assignment.sikshasathi.tech
  sslRedirect: "true"
  sslCertificate: wildcard-sikshasathi-tech
health:
  path: /
