apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reporting-service
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: oci://devacr301225.azurecr.io/helm/service
      chart: service
      targetRevision: 1.0.2
      helm:
        passCredentials: true
        valueFiles:
          - $values/helm/values.yaml

    - repoURL: https://github.com/ITAssetManagementSystem/ReportingService.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: it-reporting

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
